### ISSUE TITLE
Binary encoding causes issues with some text characters

### ISSUE THREAD

**Issue by thomashigginbotham** [superjose/polymer-sass#1]
Is there a reason to use binary encoding instead of UTF-8 when writing out the file contents? This causes problems with some characters (e.g., ©)

Suggested fix:

`file.contents = new Buffer(contents.replace(regEx, injectSassContent), 'utf8');`

**Comment by superjose** [comment]
Great! There is no special reason. I'll update the code! Thanks for letting me know!
