### ISSUE TITLE
Something gone wrong

### ISSUE THREAD

**Issue by ebatgerel** [superjose/polymer-sass#3]
Hello Jose. Btw thanks for this gulpfile. I have a problem with some file. When i compiled it its worked perfect but last element result gone wrong.

![Failed](https://user-images.githubusercontent.com/16677052/37440291-0bfd0c06-2837-11e8-9fce-94b4da616557.PNG)

**Comment by superjose** [comment]
@ebatgerel Hi!😁Glad you're enjoying it!
Would you mind sharing posting the original html?

**Comment by ebatgerel** [comment]
```
<dom-module id="swiper-css">
  <template>
    <!-- Start Style -->
      <style>
      </style>
    <!-- End Style -->
  </template>
</dom-module>
```

Here is my HTML structure. Others are like this and compiled well. Maybe its from swiper.scss ?

**Comment by superjose** [comment]
I'm going to look into it. I'll report back. (Will do it in approx 10 hours).

**Comment by superjose** [comment]
@ebatgerel I haven't been able to reproduce the issue. Could you check that you have a valid .scss? Have you tried linting the file? 

I've had those problems in the past, and it's been somewhat painful, and it has been because of a malformed scss.

**Comment by ebatgerel** [comment]
I am using swiper js. And tried to compile swiper.min.css. But i first convert css file into scss. And its gives me above example

**Comment by superjose** [comment]
@ebatgerel I see. I'll look into that! Thanks!!

**Comment by superjose** [comment]
@ebatgerel Came back. Busy with other things. I know this is going to sound pretty horrible from me, meanwhile try manually including the css inside the component manually. As soon as I have some time available I"ll look into it.

**Comment by ebatgerel** [comment]
@superjose thanks

**Comment by superjose** [comment]
@ebatgerel Sorry for taking this long. I've taken a look into it and I saw that the code transpiled 1 on 1. I haven't used Polymer 2 yet. So I need to check where the problems lie, because I think that there must be something with  `<custom-styles></custom-styles>.` I have to update the main page anyways. 

I have yet to try the results.

**Comment by ebatgerel** [comment]
@superjose  Okay.

**Comment by superjose** [comment]
Shoot the tags got stripped away, see the edited post.

**Comment by ebatgerel** [comment]
i see the post but can't see different what was the first post ? ... :)

**Comment by superjose** [comment]
@ebatgerel: 
Check if you're using `custom-styles`. I'll definitely look deep into this issue. Are you using Polymer 2?

**Comment by ebatgerel** [comment]
Yes i am using polymer 2. And i not used `custom-styles`

**Comment by superjose** [comment]
@ebatgerel 
I haven't forgotten about you. Still, lot's of things going on (Trying to work on a Startup, taking lots of time, and polymer-cli not cooperating). Just realized that the plugin depends on NodeSass which is not compatible with the latest versions of Node. 

[AHhan](https://stackoverflow.com/a/37666406/1057052) from StackOverflow developed a plugin. You may want to check it out while I still get some time to work on this. 

https://github.com/drdreo/StyleModuleInjectPlugin

**Comment by ebatgerel** [comment]
Thanks for this

**Comment by superjose** [comment]
I'm so sorry for writing almost 3 months later. I'm going to look into this issue, today, and I'm going to upgrade the repo to Polymer 3.

**Comment by ebatgerel** [comment]
sounds good :)

**Comment by superjose** [comment]
Just to give a quick update. I've started working on it. It's already half-way through. It's nothing fancy, and there's still some work that need to be done in the developer's end.

**Comment by superjose** [comment]
Well, well. Long story short, I decided to start working on a webpack loader, and so far I've been able to achieve an alpha level. 

In English: Basic functionality is working. Need to work in caching mechanism, async loading, and other goodies. So far, so good!

Here's the repo!

https://github.com/superjose/polymer-css-webpack-loader

**Comment by superjose** [comment]
Yes. I'm still planning on updating this repo with a gulp file.

**Comment by superjose** [comment]
@ebatgerel I finalized the first version for Webpack and Polymer 3!. 
https://github.com/superjose/polymer-css-loader/
https://www.npmjs.com/package/polymer-css-loader

**Comment by ebatgerel** [comment]
Good job. Nut i am still using polymer 2.0 :) BTW thanks for this.

**Comment by superjose** [comment]
@ebatgerel I will still update this for 2.0!!! This week!

**Comment by superjose** [comment]
@ebatgerel Sorry for being so silly. I haven't used Polymer 2, and I didn't realize it works the same as Polymer 1 when it comes to styling. I'm looking to the problem right now...

**Comment by superjose** [comment]
@ebatgerel After going deep I still haven't figured out where the CSS is wrong. I used diff checker to spot any differences https://www.diffchecker.com/diff, and I couldn't spot any differences.

I did notice that it is going to be challenging including Swiper in Polymer. I think the problem lies in JavaScript and not CSS. Whenver you use:
```
 new Swiper ('.swiper-container', {
    // Optional parameters
    direction: 'vertical',
    loop: true,

    // If we need pagination
    pagination: {
      el: '.swiper-pagination',
    },

    // Navigation arrows
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },

    // And if we need scrollbar
    scrollbar: {
      el: '.swiper-scrollbar',
    },
  })

```
It seems it performs a document.querySelector('.swiper-container') which is completely inaccessible to Swiper since your element is encapsulated by the shadow DOM. 

Could you verify this approach? Have you had it working? 
I could only think on either modifying swiper so you can pass the object directly, which you'll be able to do by using `this.shadowRoot.querySelector('.swiper-container')` or do some hacky thing with the HTML so it doesn't get encapsulated by the shadow DOM, which I wouldn't recommend.

**Comment by ebatgerel** [comment]
@superjose  thanks man i am solved my problem.

**Comment by superjose** [comment]
@ebatgerel Sorry for not helping out. How did you end up solving the issue?
