### ISSUE TITLE
Import additional sass

### ISSUE THREAD

**Issue by ebatgerel** [superjose/polymer-sass#4]
Is it possible to import external sass file ? Like: 

```
my-component.html
my-component.scss
```
and on scss file with: 

```
@import '../variables';
```
etc ?

**Comment by superjose** [comment]
Yes! Look at **SASS Imports** in the README. 

There are a couple of ways to do it. 

#1): 
You have it under a _styles folder: 
```
app/ 
   - elements/
      - my-component.html
      - my-component.scss
    - styles/
      _mybase.scss; 
```
Then you call it like:
`@import '../styles/_mybase'; `

Note that styles is in the same level as elements. 

#2): If you want to have it in other folder that's not /styles/, then:
Check: 
Inside the gulpfile
`var includePaths = ['app/elements/**/']`, and app/styles, which is hardcoded to the gulpfile!

Let me know!
